/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * タイトル
 * OpenAPI spec version: 2.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type PutUserId200 = {
  id?: number;
  username?: string;
};

export type GetUserId200 = {
  id?: number;
  username?: string;
};





  /**
 * ユーザー情報取得
 */
export const getUserId = <TData = AxiosResponse<GetUserId200>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/user/${id}`,options
    );
  }

/**
 * ユーザー情報取得
 */
export const putUserId = <TData = AxiosResponse<PutUserId200>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/user/${id}`,undefined,options
    );
  }

export type GetUserIdResult = AxiosResponse<GetUserId200>
export type PutUserIdResult = AxiosResponse<PutUserId200>
