/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * タイトル
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export type GetUserId200 = {
  id?: number;
  username?: string;
};





  /**
 * ユーザー情報取得
 */
export const getUserId = <TData = AxiosResponse<GetUserId200>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/user/${id}`,options
    );
  }

export type GetUserIdResult = AxiosResponse<GetUserId200>
